import {TwitterApi} from 'twitter-api-v2';import crypto from 'crypto';import {getTwitterTokenByUserId,saveTwitterToken} from '@/lib/supabase';import type {TwitterToken,TwitterReplyMeta} from '@/lib/types';
export function isTwitterConfigured(){return !!process.env.TWITTER_CLIENT_ID&&!!process.env.TWITTER_CLIENT_SECRET}
export function twitterRedirectUri(){return `${process.env.TWITTER_REDIRECT_URI_BASE??'http://localhost:3000'}/api/auth/twitter/callback`}
const SCOPES=['tweet.read','tweet.write','users.read','dm.read','dm.write','offline.access'];
export interface PkceSession{codeVerifier:string;codeChallenge:string;state:string;createdAt:number}
export function generatePkce(){const codeVerifier=crypto.randomBytes(32).toString('base64url');return {codeVerifier,codeChallenge:crypto.createHash('sha256').update(codeVerifier).digest('base64url'),state:crypto.randomBytes(16).toString('hex'),createdAt:Date.now()}}
export function buildAuthUrl(pkce:PkceSession){if(!isTwitterConfigured()){return `/api/auth/twitter/callback?mock=1&state=${encodeURIComponent(pkce.state)}`};const p=new URLSearchParams({response_type:'code',client_id:process.env.TWITTER_CLIENT_ID!,redirect_uri:twitterRedirectUri(),scope:SCOPES.join(' '),state:pkce.state,code_challenge:pkce.codeChallenge,code_challenge_method:'S256'});return `https://twitter.com/i/oauth2/authorize?${p}`}
export async function exchangeCodeForToken(code:string,verifier:string,isMock=false){if(isMock||!isTwitterConfigured()){const h=crypto.createHash('sha256').update(code).digest('hex');return {accessToken:`mock_access_${h.slice(0,24)}`,refreshToken:`mock_refresh_${h.slice(24,48)}`,expiresAt:new Date(Date.now()+7200000),scope:SCOPES.join(' '),twitterUserId:h.slice(0,12),twitterHandle:`mockuser_${h.slice(0,4)}`}}const client=new TwitterApi({clientId:process.env.TWITTER_CLIENT_ID!,clientSecret:process.env.TWITTER_CLIENT_SECRET!} as any);const result=await client.oauth2.token({code,codeVerifier:verifier,redirectUri:twitterRedirectUri()});const me=await new TwitterApi(result.access_token).v2.me();return {accessToken:result.access_token,refreshToken:result.refresh_token??'',expiresAt:new Date(Date.now()+(result.expires_in??7200)*1000),scope:typeof result.scope==='string'?result.scope:SCOPES.join(' '),twitterUserId:me.data.id,twitterHandle:me.data.username}}
class Mock{constructor(private t:TwitterToken){}get v2(){return {tweet:async(text:string)=>({data:{id:`mock_${Date.now()}`,text}}),reply:async(text:string,id:string)=>({data:{id:`mock_reply_${Date.now()}`,text}}),search:async(q:string)=>({data:[],meta:{result_count:0}}),sendDm:async(_id:string,_text:string)=>({data:{dm_event_id:`mock_dm_${Date.now()}`}})}}}
async function clientFor(userId:string){const token=await getTwitterTokenByUserId(userId);if(!token)throw new Error('No X account connected for user');if(!isTwitterConfigured())return {client:new Mock(token),token};return {client:new TwitterApi(token.accessToken),token}}
export function detectExternalUrls(t:string){return /\b(https?:\/\/|www\.)[^\s]+/i.test(t)}
export function estimatePostCost(t:string){return detectExternalUrls(t)?0.215:0.015}
export async function postRootTweet(userId:string,text:string){const {client}=await clientFor(userId);const r=await client.v2.tweet(text);return {tweetId:r.data.id,costUsd:estimatePostCost(text)}}
export async function postReplyTweet(userId:string,text:string,inReplyToTweetId:string){const {client}=await clientFor(userId);const r=await client.v2.reply(text,inReplyToTweetId);return {tweetId:r.data.id,costUsd:estimatePostCost(text)}}
export async function fetchReplies(userId:string,parentTweetId:string):Promise<TwitterReplyMeta[]>{const {client}=await clientFor(userId);if(client instanceof Mock)return [];const r=await client.v2.search(`conversation_id:${parentTweetId}`,{max_results:100,'tweet.fields':['author_id','conversation_id']});return r.tweets.map((t:any)=>({tweetId:t.id,text:t.text??'',authorId:t.author_id??''}))}
export async function sendDirectMessage(userId:string,recipientTwitterId:string,text:string){const {client}=await clientFor(userId);if(client instanceof Mock){const r=await client.v2.sendDm(recipientTwitterId,text);return {dmEventId:r.data.dm_event_id}}const r=await client.v2.sendDm({recipient_id:recipientTwitterId,text});return {dmEventId:r.dmEventId??`dm_${Date.now()}`}}
